#!/usr/bin/env bash
#To file, or not to file
if [ -e "school" ];then
  echo "school file exists"
  if [ -n "school" ]; then
    echo "school file  empty"
  else
    echo "school file is is not empty"
  fi
  if [ -f "school" ];then
    echo "school is a regular file"
  fi
else 
  echo "school file does not exist"
fi
